# -*- coding: utf-8 -*-
# @Time    : 2022/11/16
# @Author  : chenxuehong
# @File    : app.yaml
# @Remake  : app相关配置

appActivity:
  browser: com.huawei.browser.Main2
  tencent: com.tencent.mm.ui.LauncherUI
  chanmama: .operation.home.activity.LauncherActivity