# -*- coding: utf-8 -*-
# @Time    : 2022/11/15
# @Author  : chenxuehong
# @File    : path.yaml
# @Remake  : web相关配置


# aaa主页地址
host:
 test: https://aaa
 stage: https://aa
 release: https://a

# bbb主页地址
cmm_host:
 test: https://bbb
 stage: https://sbb
 release: https://b

# ccc主页地址
cgj_host:
 test: https://ccc
 stage: https://cc
 release: https://c

# aaa子页面路径
cxh_path:
 login: /login # 登录页面
 dashboard: /dashboard
 authorLib: /authorLib
 noteLib: /noteLib
 brandLib: /brandLib
 kindLib: /categoryLib
 goodsLib: /goodsLib
 liveLib: /liveLib
 hotKeywordLib: /hotWordsLib
 topicLib: /topicLib

# bbb子页面路径
cmm_path:
 login: /login  # 登录页面
 home: /douyin
 dashboard: /dashboard
 authorLib: /bloggerRank
 goodsLib: /promotionRank
 liveLib: /liveSearch
 awemeLib: /awemeRank
 storeLib: /tikShopStore
 brandLib: /brandSearch


# ccc子页面路径
cgj_path:
 home: /home
 anchorManage: /anchor-manage
 goodsOverview: /product-overview
 thousandAccount: /thousand-account
 userPortrait: /user-portrait
 videoManage: /video-manage



