# -*- coding: utf-8 -*-
# @Time    : 2022/11/15
# @Author  : chenxuehong
# @File    : web.yaml
# @Remake  : web相关配置


# 蝉小红主页地址
home:
 test: https://cmm-xhs-test.cds8.cn
 stage: https://cmm-xhs-stage.cds8.cn
 release: https://www.chanxiaohong.com
# 蝉小红子页面路径
path:
 login: /login
 authorLib: /authorLib
 noteLib: /noteLib


