# -*- coding: utf-8 -*-
# @Time    : 2022/11/15
# @Author  : chenxuehong
# @File    : web_host.yaml
# @Remake  : web相关配置


# 蝉小红主页地址
host:
 test: https://cmm-xhs-test.cds8.cn
 stage: https://cmm-xhs-stage.cds8.cn
 release: https://www.chanxiaohong.com

# 蝉妈妈主页地址
cmm_host:
 test: https://sv-test.cds8.cn
 stage: https://sv-stage.cds8.cn
 release: https://www.chanmama.com

# 蝉管家主页地址
cgj_host:
 test: https://changkong-test.cds8.cn
 stage: https://changkong-stage.cds8.cn
 release: https://www.changuanjia.com

# 蝉小红子页面路径
cxh_path:
 login: /login
 authorLib: /authorLib
 noteLib: /noteLib
 dashboard: /dashboard

# 蝉妈妈子页面路径
cmm_path:
 login: /login
 home: /douyin
 dashboard: /dashboard

# 蝉管家子页面路径
cgj_path:
 home: /home


